hide sold preloaded flips
matthias-luger/hypixel-react pull request #1020
Opened 2023-01-03 02:59 UTC by matthias-luger

fixes #1019

2023-01-03 09:05 UTC, Ekwav requested changes

2023-01-03 09:05 UTC, Ekwav commented on components/Flipper/Flipper.tsx
> +    let [flips, setFlips] = useState<FlipAuction[]>(
What about new flips getting sold?
The statehook is only created once when the site loads, isn't it?

2023-01-06 18:37 UTC, matthias-luger commented on components/Flipper/Flipper.tsx
> +    let [flips, setFlips] = useState<FlipAuction[]>(
If a new flip comes in, it is checked for being sold: 
![grafik](https://user-images.githubusercontent.com/58751503/211076633-281c1982-e007-47fd-90e5-34713a4f2053.png)

Also, if I get the websocket event that a flip was sold, it is removed, if the checkbox is checked: 
![grafik](https://user-images.githubusercontent.com/58751503/211076791-9f682b57-16a9-4568-bda5-868a4dcc22e1.png)

2023-01-06 19:27 UTC, Ekwav approved these changes
LGTM! :)

2023-01-06 19:27 UTC, merged