couple of changes
matthias-luger/hypixel-react pull request #1033
Opened 2023-01-16 12:17 UTC by pennacap

- Removed dependence on the `uuid` module, instead using `crypto.randomUUID`
- Fixed typos, added a bit of styling
- Prevented `null` from showing up in new items

2023-01-16 13:44 UTC, pennacap commented
Wait hold on I found a bug with SSRing

2023-01-16 14:10 UTC, pennacap commented
i reverted the uuids cuz i didn't wanna deal with using diff functions for ssr and csr

2023-01-16 17:49 UTC, matthias-luger requested changes

2023-01-16 17:49 UTC, matthias-luger commented on components/Hyauctions/Hyauctions.tsx
> +import Link from 'next/link';
Please remove all unnecessary ";"

2023-01-16 17:49 UTC, matthias-luger commented on components/MainApp/MainApp.tsx
> +import { isClientSideRendering } from '../../utils/SSRUtils';
move the import one line up and put the empty line below

2023-01-16 17:49 UTC, matthias-luger commented on components/FilterElement/FilterElements/PlayerFilterElement.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on components/Flipper/Flipper.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on components/MainApp/MainApp.tsx
> +                buttonText="Yes, I Understand"
Not a native speaker so I might be incorrect, but why would "Understand" be capitalized here?

2023-01-16 17:49 UTC, matthias-luger commented on components/ShareButton/ShareButton.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on components/Search/Search.tsx
> +        paddingBottom:'3vh'
I do not think this looks better. Please remove this
![grafik](https://user-images.githubusercontent.com/58751503/212729126-105e6e4b-6a7d-4818-93a7-0d9e2b19383b.png)

2023-01-16 17:49 UTC, matthias-luger commented on components/Startpage/Startpage.tsx
> +    newItems = newItems.filter((search)=>search.name!='null');
move this filter into the `pages/index.html` in the `getServerSideProps` function where the data gets loaded. Otherwise it gets needlessly transfered.

2023-01-16 17:49 UTC, matthias-luger commented on components/Startpage/Startpage.tsx
> +                            {newItems.filter(search=>search.name!='null').map(search => {
this filter is not needed after the task above

2023-01-16 17:49 UTC, matthias-luger commented on components/Startpage/Startpage.tsx
> +        }
This check is not needed anymore after the task below

2023-01-16 17:49 UTC, matthias-luger commented on components/Tooltip/Tooltip.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on components/TransferCoflCoins/TransferCoflCoinsSummary.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on components/TransferCoflCoins/TransferCoflCoinsSummary.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on utils/CoflCoinsUtils.tsx
> +
remove empty line

2023-01-16 17:49 UTC, matthias-luger commented on styles/globals.css
> +}
remove the styling in the Flipper.module.css as it is now defined twice

2023-01-17 06:26 UTC, pennacap commented on components/MainApp/MainApp.tsx
> +                buttonText="Yes, I Understand"
just stylistically, no real reason, changing it back is fine

2023-01-17 07:10 UTC, pennacap commented
I think I resolved the issues, please tell me if I missed a few

2023-01-17 14:19 UTC, matthias-luger requested changes

2023-01-17 14:19 UTC, matthias-luger commented on components/Search/Search.tsx
> +        paddingBottom:'0.5vh'
Why add this? This looks excactly like before

2023-01-17 16:24 UTC, pennacap commented
fixed, although it should be slightly smaller, ill try and see whats wrong tom

2023-01-24 17:50 UTC, merged