switched to http where possible
matthias-luger/hypixel-react pull request #109
Opened 2021-05-25 20:15 UTC by Ekwav

fixes #99

2021-05-26 06:28 UTC, matthias-luger commented on src/api/HttpHelper.tsx
> +export let httpApi:  HttpApi = {
please use the same formatting style as everywhere else (spaces)

2021-05-26 06:28 UTC, matthias-luger commented on src/api/HttpHelper.tsx
> +function getOrGenerateUUid() : string {
please use the same formatting style as everywhere else (spaces)

2021-05-26 06:29 UTC, matthias-luger commented on src/api/HttpHelper.tsx
> +function init(): void {
remove unused function

2021-05-26 06:29 UTC, matthias-luger commented on src/api/HttpHelper.tsx
> +    if(request.mId)
url into constant variable?

2021-05-26 06:30 UTC, matthias-luger requested changes
improve according to comments

2021-05-26 14:04 UTC, matthias-luger requested changes
improve performance (lighthouse)

2021-05-26 15:02 UTC, Ekwav commented
> improve performance (lighthouse)

out of scope

2021-05-27 18:14 UTC, Flou21 commented on public/preScript.js
> +*/
why?

2021-05-27 18:18 UTC, Flou21 approved these changes

2021-05-27 18:18 UTC, merged