Update claim account text
matthias-luger/hypixel-react pull request #1099
Opened 2023-05-04 23:49 UTC by matthias-luger

fixes #1095

2023-05-04 23:50 UTC, matthias-luger commented
@Ekwav Feel free to add/change this text as you see fit :)

2023-05-05 20:03 UTC, Ekwav requested changes

2023-05-05 20:03 UTC, Ekwav commented on components/ClaimAccount/ClaimAccount.tsx
> +                    ref system.
```suggestion
                    The referral bonus for inviting someone is only awarded after verifying with a minecraft account.  
                    You receive free test premium after you verified your account.
                    This is to prevent people from abusing the ref system by creating new emails.
```

2023-05-05 20:03 UTC, Ekwav commented on components/ClaimAccount/ClaimAccount.tsx
> +                    for our flip tracking feature.
```suggestion
                    As part of our fairness system unverified accounts receive flips delayed. 
                    Some parts (like the in game `/cofl profit`) use the list of verified accounts to compute summaries over all your minecraft accounts.
```

2023-05-05 21:12 UTC, merged