implemented clear flips
matthias-luger/hypixel-react pull request #180
Opened 2021-06-19 04:41 UTC by matthias-luger

fixes #175

2021-06-19 10:13 UTC, Ekwav requested changes
How about moving the utility options into a separate column instead of splitting the filters into two.

2021-06-19 10:13 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                    <Form.Label style={{ cursor: "pointer" }} onClick={onArrowRightClick}>Clear flips:</Form.Label>
the onClick is binds to the wrong function.
I suggest you add the onClick onto the `Form.Group` element.

2021-06-21 22:31 UTC, matthias-luger commented
@Ekwav general styling changes should not be included in this issue => this issue is ready for merge

2021-06-22 15:40 UTC, Ekwav approved these changes

2021-06-22 15:40 UTC, merged