Paypal implement
matthias-luger/hypixel-react pull request #197
Opened 2021-06-24 16:59 UTC by Flou21

2021-06-25 12:07 UTC, matthias-luger requested changes

2021-06-25 12:07 UTC, matthias-luger commented on src/utils/Payment/PaymentUtils.tsx
> +    products = products.sort((a: Product, b: Product) => {
shouldnt products.sort((a,b)=>a.premiumDuration-b.premiumDuration) als work?

2021-06-25 14:47 UTC, Flou21 commented on package.json
> +        "start": "BROWSER=none craco start",
nobody wants that

2021-06-28 17:01 UTC, matthias-luger requested changes

2021-06-28 17:01 UTC, matthias-luger commented on src/api/ApiHelper.tsx
> +                    apiErrorHandler(RequestType.RECENT_AUCTIONS, error, {orderId, days});
use a variable (look at getRecentAuctions)

2021-07-02 11:44 UTC, Flou21 commented
still waiting..

2021-07-02 14:19 UTC, merged