App review
matthias-luger/hypixel-react pull request #28
Opened 2021-02-15 17:37 UTC by Flou21

2021-02-15 17:37 UTC, Flou21 commented
Warum funktioniert bootstrap nicht standardmäßig, nur mit cdn?

2021-02-16 17:39 UTC, matthias-luger requested changes

2021-02-16 17:39 UTC, matthias-luger commented on src/api/ApiHelper.tsx
> +                            console.log(product);
remove console.log

2021-02-16 17:39 UTC, matthias-luger commented on src/api/ApiHelper.tsx
> +                    let mappedPrices = prices.data.map((price: any) => {
Extract functionality into ApiResponseParser

2021-02-16 17:39 UTC, matthias-luger commented on src/api/ApiHelper.tsx
> +                        resolve(products.data.filter((product: any) =>
extract functionality into ResponseParser

2021-02-16 17:39 UTC, matthias-luger commented on src/api/WebsocketHelper.tsx
> +        console.log({e});
remove console.log

2021-02-16 17:39 UTC, matthias-luger commented on src/components/Payment/Payment.tsx
> +  const getProducts = async () => {
remove async await

2021-02-16 17:39 UTC, matthias-luger commented on src/components/Payment/Payment.tsx
> +  const getProductsJsx = async (): Promise<JSX.Element> => {
Why are you doing it like this?
Just put the products into a state-variable.
Remove async await
Remove col-classNames (very large files)

2021-02-16 17:39 UTC, matthias-luger commented on src/components/Payment/Payment.tsx
> +  const roundToTwo = (param: number): number => Math.round(param * 10 ** 2) / 10 ** 2;
better: Math.round((num + Number.EPSILON) * 100) / 100

2021-02-16 17:39 UTC, matthias-luger commented on src/components/Payment/Payment.tsx
> +  useEffect(() => { setProductsJsx() }, []);
use effect goes to the top of the file

2021-02-16 17:39 UTC, matthias-luger commented on src/components/Payment/Payment.tsx
> +  const setProductsJsx = async () => setProductsListJsx(await getProductsJsx())
remove async await

2021-02-16 17:39 UTC, matthias-luger commented on src/components/Payment/Payment.tsx
> +  const getProductsJsx = async (): Promise<JSX.Element> => {
JSX variables or functions go to the bottom of the file

2021-02-16 17:39 UTC, matthias-luger commented on src/components/Search/Search.tsx
> +import Payment from '../Payment/Payment'
remove unused import

2021-02-16 17:39 UTC, matthias-luger commented on src/components/SubscriptionList/SubscriptionList.tsx
> +import Payment from '../Payment/Payment';
remove unused import

2021-02-16 17:39 UTC, matthias-luger commented on src/components/SubscriptionList/SubscriptionList.css
> +.buy-prime-button {
remove unused class

2021-02-16 17:39 UTC, matthias-luger commented on src/react-app-env.d.ts
> +    productId: string|null,
format code

2021-02-16 17:39 UTC, matthias-luger commented on src/react-app-env.d.ts
> +    value: float
why float and not number

2021-02-16 17:39 UTC, matthias-luger commented on src/react-app-env.d.ts
> +    value: string
is type string for a value really correct?

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/GoogleUtils.tsx
> +export function getPackageName () {
why is this a function and not a constant

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/GooglePlayProvider.tsx
> +    public async getProducts(): Promise<Product[]> {
remove async await

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/GooglePlayProvider.tsx
> +export default class GooglePlayProvider extends AbstractPaymentProvider {
we use functional components

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/AbstractPaymentProvider.tsx
> +export default abstract class AbstractPaymentProvider {
use functional components

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/GooglePlayProvider.tsx
> +    public async pay(product: Product): Promise<Product> {
remove async await

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/GooglePlayProvider.tsx
> +    public async checkIfPaymentIsPossible(): Promise<boolean> {
remove async await

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/GooglePlayProvider.tsx
> +    private async setDigitalGoodsService() {
remove async await

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/GooglePlayProvider.tsx
> +    private async validatePaymentToken(token: string, product: Product): Promise<boolean> {
remove async await

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/PaymentUtils.tsx
> +export default async function availablePaymentProvider(): Promise<AbstractPaymentProvider> {
function should be called PaymentUtils

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/StripePaymentProvider.tsx
> +export default class StripePaymentProvider extends AbstractPaymentProvider {
use functional components

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/StripePaymentProvider.tsx
> +        //TODO move this function
no TODO

2021-02-16 17:39 UTC, matthias-luger commented on src/utils/Payment/StripePaymentProvider.tsx
> +        api.pay(this.stripePromise, product);
you forgot the await
remove the async await

2021-02-26 21:41 UTC, matthias-luger approved these changes

2021-02-26 21:41 UTC, merged