improved premium site
matthias-luger/hypixel-react pull request #327
Opened 2021-07-29 20:32 UTC by matthias-luger

(mostly?) fixes #321
fixes #323

2021-07-29 20:35 UTC, Ekwav approved these changes

2021-07-29 20:45 UTC, Ekwav requested changes

2021-07-29 20:45 UTC, Ekwav commented on src/components/Premium/Premium.tsx
> +                    <p>I want Premium! Get me <a href="#buyPremium">there</a>.</p> :
```suggestion
                    <p><a href="#buyPremium">I want Premium! </a>.</p> :
```

2021-07-29 20:45 UTC, Ekwav commented on src/components/Premium/Premium.tsx
>                              Account: {getAccountString()}
account should be displayed for all users not just for premium

2021-07-29 22:08 UTC, matthias-luger commented
Please test the Premium page as a user who is logged in without premium

2021-07-30 10:24 UTC, Ekwav approved these changes

2021-07-30 10:24 UTC, merged