show missed profit
matthias-luger/hypixel-react pull request #339
Opened 2021-07-31 00:55 UTC by matthias-luger

fixes #293

2021-07-31 01:04 UTC, Flou21 commented
created temp environment: https://temp-env-sky-339.flou21.de

2021-07-31 10:55 UTC, Ekwav requested changes
Please move this header below the flipper-card into its own card.
Make it collapsed by default and display only 
"Missed Profit: XY " as the title.
In its current form its way to annoying especially if you click on a flip and it scrolls up.

2021-07-31 10:55 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                                    tooltipContent={<span>The premium flipper is not delayed. Therefor you get access to the most profitable flips. Currently really good flips are alr
```suggestion
                                                    tooltipContent={<span>The premium flipper is not delayed. Therefor you would get access to the most profitable flips and not miss out on this amount of profit.</span>} />
```

2021-07-31 13:42 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-07-31 14:07 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-07-31 14:11 UTC, Ekwav requested changes

2021-07-31 14:11 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                                    tooltipContent={<span>The premium flipper is not delayed. Therefor you would get access to the most profitable flips and not miss out on this amoun
```suggestion
                                                    tooltipContent={<span>This is the sum of the field 'Estimated profit' of the flips that were already sold when you received them. It represents the extra coins you could earn if you purchased our premium plan.</span>} />
```

2021-07-31 14:11 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                        <legend>You dont have Premium?</legend>
```suggestion
                                        <legend>You don't have Premium</legend>
```

2021-07-31 14:11 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                            <li>Total found flips: {numberWithThousandsSeperators(missedInfo.totalFlips)}</li>
```suggestion
                                            <li>Total flips received: {numberWithThousandsSeperators(missedInfo.totalFlips)}</li>
```

2021-07-31 14:11 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                <Card.Title>Missed profit</Card.Title>
```suggestion
                                <Card.Title>Flipper summary</Card.Title>
```

2021-07-31 14:13 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-07-31 14:34 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-07-31 14:40 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-08-01 21:05 UTC, Ekwav requested changes

2021-08-01 21:05 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                                You don't have Premium?
```suggestion
                                                You don't have Premium
```

2021-08-01 21:05 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                                    <Card className="flipper-summary-card">
this card should grow if there is space

2021-08-02 16:53 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-08-02 16:56 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-08-02 17:46 UTC, Ekwav requested changes

2021-08-02 17:46 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
> +                !isLoading && isLoggedIn && hasPremium ?
I am pretty sure that you want to revert this

2021-08-02 18:27 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-339.flou21.de

2021-08-02 19:55 UTC, Ekwav approved these changes

2021-08-02 19:56 UTC, merged