implemented volume filter
matthias-luger/hypixel-react pull request #359
Opened 2021-08-03 21:00 UTC by matthias-luger

filter style change

2021-08-03 21:07 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-359.flou21.de

2021-08-04 14:29 UTC, Ekwav requested changes
Looks dope, greatly reduces the height of the options

2021-08-04 14:29 UTC, Ekwav commented on src/components/Flipper/Flipper.tsx
>                              <Form.Group onClick={onArrowRightClick}>
This isn't the correct click handler for this.
Please display a "Coming Soon" Tooltip for this element and remove the onClick for now

2021-08-04 14:29 UTC, Ekwav commented on src/components/Flipper/FlipperFilter/FlipperFilter.tsx
> +            <Form.Control onChange={onMinVolumeChange} className="flipper-filter-formfield" type="number" max={60} disabled={!props.isLoggedIn && !freeLoginFilters} />
could negative numbers be used to invert the filter to "maxVolume" ?

2021-08-04 15:00 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-359.flou21.de

2021-08-04 21:00 UTC, Ekwav approved these changes

2021-08-04 21:00 UTC, merged