improved search style
matthias-luger/hypixel-react pull request #361
Opened 2021-08-04 22:19 UTC by matthias-luger

2021-08-04 22:26 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-04 23:34 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-04 23:35 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-05 16:13 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-05 17:42 UTC, Ekwav requested changes
Please make the input the the suggestion text to be in one row

2021-08-05 18:13 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-05 18:16 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-05 18:21 UTC, Ekwav requested changes
Why is the text in the input bigger than the suggestions?
The search icon should have the same style and position than the preview images

2021-08-05 18:21 UTC, Ekwav commented on src/components/Search/Search.tsx
> +                <Form.Group style={{ display: "flex", justifyContent: "center", alignContent: "center", marginBottom: 0, borderBottomWidth: 0 }}>
make this a class

2021-08-05 18:25 UTC, Ekwav commented
The tests don't pass after this change

2021-08-05 18:25 UTC, Ekwav commented
The tests don't pass after this change

2021-08-05 21:57 UTC, matthias-luger commented
I guess then there wont be a search style improvement.
Sad, because it really looks good and improves the search result loading. 👎

2021-08-06 00:11 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-06 16:30 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-06 16:36 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-06 16:37 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-06 17:05 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-361.flou21.de

2021-08-06 17:18 UTC, merged