Display flip properties
matthias-luger/hypixel-react pull request #368
Opened 2021-08-05 22:55 UTC by matthias-luger

fixes #338 

only merge with #336

2021-08-05 23:06 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-368.flou21.de

2021-08-06 00:02 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-368.flou21.de

2021-08-06 16:42 UTC, Ekwav requested changes
I am missing any option to remove the horizontal lines.
There may now be two lines next to each other which make not a lot of sense

2021-08-06 21:01 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-368.flou21.de

2021-08-06 21:09 UTC, Ekwav requested changes

2021-08-06 21:09 UTC, Ekwav commented on src/components/Flipper/FlipCustomize/FlipCustomize.tsx
> +        maxExtraInfoFields: 3
this object is redundant

2021-08-07 00:14 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-368.flou21.de

2021-08-07 09:46 UTC, Ekwav approved these changes

2021-08-07 09:46 UTC, merged