About
matthias-luger/hypixel-react pull request #377
Opened 2021-08-08 20:32 UTC by matthias-luger

fixes #376

2021-08-08 20:37 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-377.flou21.de

2021-08-09 19:40 UTC, Ekwav requested changes

2021-08-09 19:40 UTC, Ekwav commented on src/pages/About/About.tsx
> +                    <h3>Legal</h3>
```suggestion
                    <h2>Legal</h2>
<p>We are not affiliated with Mojang nor HyPixel</p>
```

2021-08-09 19:40 UTC, Ekwav commented on src/pages/About/About.tsx
> +                    <h3>Player Heads</h3>
```suggestion
<h2>Credits</h2>
                    <h3>Player Heads</h3>
```

2021-08-09 19:40 UTC, Ekwav commented on src/pages/About/About.tsx
> +                    <p><a href="https://mc-heads.net/">mc-heads</a> and <a href="https://craftatar.com">craftatar</a></p>
```suggestion
                    <p>Are provided by<a href="https://mc-heads.net/">mc-heads</a> and <a href="https://craftatar.com">craftatar</a></p>
```

2021-08-09 19:40 UTC, Ekwav commented on src/pages/About/About.tsx
> +                    <p><a href="https://sky.coflnet.com/api">https://sky.coflnet.com/api</a></p>
```suggestion
                    <p><a href="https://sky.coflnet.com/api">https://sky.coflnet.com/api</a></p>
<p>If you use it please link to <a href="https://sky.coflnet.com/data">https://sky.coflnet.com/data</a></p>
```

2021-08-10 16:41 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-377.flou21.de

2021-08-10 16:42 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-377.flou21.de

2021-08-10 16:45 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-377.flou21.de

2021-08-10 16:49 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-377.flou21.de

2021-08-10 17:56 UTC, Ekwav requested changes

2021-08-10 17:56 UTC, Ekwav commented on src/pages/About/About.tsx
> +                    <p>Are provided by<a href="https://mc-heads.net/">mc-heads</a> and <a href="https://craftatar.com">craftatar</a></p>
```suggestion
                    <p>Are provided by <a href="https://mc-heads.net/">mc-heads</a> and <a href="https://craftatar.com">craftatar</a></p>
```

2021-08-10 18:29 UTC, merged

2021-08-10 18:39 UTC, Flou21 commented
[CI] created a pr environment: https://pr-env-sky-377.flou21.de