implement white/blacklist of the backend
matthias-luger/hypixel-react pull request #455
Opened 2021-09-05 03:43 UTC by matthias-luger

fixes #432

2021-09-05 03:43 UTC, matthias-luger commented
@Ekwav I think the UI works and sends the correct data but the new backend doesnt work.

2021-09-12 10:37 UTC, Ekwav commented
There was indeed a bug when specifying a blacklist with an empty array. 
I fixed it.  
This PR should target `develop` it would break production

2021-09-12 10:40 UTC, Ekwav requested changes

2021-09-12 10:40 UTC, Ekwav commented on src/properties.js
> +    "websocketEndpoint": "wss://sky-commands.coflnet.com/skyblock",
This PR should target `develop` it would break production

2021-09-15 06:53 UTC, Ekwav requested changes
Some issues I found:
- When any filter is changed all flips are deleted.
- a date filter is displayed as timestamp
- the filters are only for "aspect of the end" it should request "*"

2021-09-21 16:58 UTC, merged