implement correct name for based auction
matthias-luger/hypixel-react pull request #456
Opened 2021-09-05 03:54 UTC by matthias-luger

fixes #441

2021-09-05 03:55 UTC, matthias-luger commented
It would be cool if the property could be renamed from ItemName to itemName like it is everywhere else.

2021-09-12 10:09 UTC, Ekwav commented
It is not called `ItemName`, it is called `name` should I rename it to `itemName` ?

2021-09-12 10:19 UTC, Ekwav commented
also this MR targets should target `dev` because the property is only available in commands

2021-09-12 10:19 UTC, Ekwav commented
also this MR targets should target `dev` because the property is only available in commands

2021-09-18 23:33 UTC, Ekwav requested changes

2021-09-18 23:33 UTC, Ekwav commented on src/utils/Parser/APIResponseParser.tsx
> +            name: auction.itemName || auction.ItemName
> It is not called `ItemName`, it is called `name` should I rename it to `itemName` ?
https://github.com/Coflnet/hypixel-react/pull/456#issuecomment-917605441

2021-09-25 12:33 UTC, Ekwav approved these changes

2021-09-25 12:33 UTC, merged