implemented method to trigger a player name refresh
matthias-luger/hypixel-react pull request #601
Opened 2021-11-20 10:04 UTC by matthias-luger

fixes #591

2021-11-20 10:05 UTC, matthias-luger commented
The request should respond with a 204 empty response code

2021-11-20 11:07 UTC, Ekwav requested changes

2021-11-20 11:07 UTC, Ekwav commented on src/components/Search/Search.tsx
> +    function handleFlipContextMenu(event) {
I don't think this is a flip context menu

2021-11-24 11:14 UTC, Ekwav approved these changes

2021-11-24 11:14 UTC, merged