implemented profile filter
matthias-luger/hypixel-react pull request #627
Opened 2021-12-21 05:07 UTC by matthias-luger

fixes #583

2021-12-23 00:58 UTC, matthias-luger commented
@Ekwav did you try it? Does it work like you intended it to?

2021-12-26 06:38 UTC, matthias-luger commented
@Ekwav ping

2021-12-27 07:17 UTC, matthias-luger commented
@Ekwav please try again

2021-12-30 09:12 UTC, matthias-luger commented
@matthias-luger ping

2021-12-31 00:18 UTC, Ekwav requested changes

2021-12-31 00:18 UTC, Ekwav commented on src/components/CraftsList/CraftsList.tsx
>          api.getProfitableCrafts(playerId, profileId).then(crafts => {
crafts are not cached via the profile id thus leading to data unexpectedly being not refreshed when a different profile is selectd

2021-12-31 00:18 UTC, Ekwav commented on src/components/CraftsList/CraftsList.tsx
> +                                    !accountInfo?.mcId ? <p>To use the the profile filter please connect your Minecraft Account</p> : ""
explain how to connect the account and what that means?

2021-12-31 04:13 UTC, Ekwav approved these changes
LGTM expect for the missing explanation which I created an issue for

2022-01-02 16:20 UTC, Ekwav approved these changes
there is a merge conflict

2022-01-03 06:53 UTC, merged