implemented player with rank filter
matthias-luger/hypixel-react pull request #651
Opened 2022-01-05 23:21 UTC by matthias-luger

fixes #647

2022-01-06 15:21 UTC, Ekwav requested changes
The filter should be applied as soon as its added (the default curently is [no player] bit that is not useable because its not applied)
[no player] should not allow the user to search for a player, if possible clicking on the input while [no player] is selected trigger the dropdown or completely hide the input.
The player search should send the player name instead of the uuid.
This is not a direct player search but a player name search.
Cake souls keep the name of the player forever.

2022-01-13 21:59 UTC, Ekwav requested changes
Can't be started 

./src/bootstrap-react.min.css
Error: PostCSS plugin postcss-purgecss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

2022-01-13 21:59 UTC, Ekwav commented on src/api/ApiHelper.tsx
> +            console.log(requestData.filter);
please remove this

2022-01-13 22:05 UTC, matthias-luger commented
@Ekwav it started for me. Maybe try npm install?

2022-01-13 22:14 UTC, matthias-luger commented
@Ekwav Please try again and do a "npm install"

2022-01-13 22:48 UTC, Ekwav approved these changes
looks good :)

2022-01-13 22:49 UTC, merged