Next server settings update
matthias-luger/hypixel-react pull request #717
Opened 2022-04-05 12:59 UTC by matthias-luger

2022-04-05 12:59 UTC, matthias-luger commented
This is based on #665

2022-04-07 12:17 UTC, matthias-luger commented
@Ekwav The backend needs to implement a new property called "copySuccessMessage". This is a setting only relevant to the UI therefore the backend didnt need to know about it until know.
I would think it should belong under the "visibility"-Property

2022-04-11 15:55 UTC, matthias-luger commented
@Ekwav There is also a UI Property I send you called "links". I put it into the visibility-Property as well

2022-04-15 10:54 UTC, Ekwav requested changes
OnlyBin and hideSold don't work

2022-04-15 10:54 UTC, Ekwav commented on utils/SettingsUtils.tsx
> +                onlyBin: data.filters.Bin === 'true'
as you requested this got changed to 
```suggestion
                onlyBin: data.onlyBin
```

2022-04-15 10:54 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +        api.setFlipSetting('maxCost', isActive)
this should map to `showHideSold`

2022-04-15 13:25 UTC, Ekwav approved these changes

2022-04-15 13:35 UTC, merged