added mod privacy settings
matthias-luger/hypixel-react pull request #799
Opened 2022-05-11 01:57 UTC by matthias-luger

2022-05-11 01:58 UTC, matthias-luger commented
TODO:
- Wait for talk regarding caching problem
- Talk about command prefixes

2022-05-11 19:10 UTC, Ekwav requested changes

2022-05-11 19:10 UTC, Ekwav commented on api/ApiHelper.tsx
> +                toast.error('You need to be logged in to purchase something.')
```suggestion
                toast.error('You need to be logged in to configure privacy settings.')
```

2022-05-11 19:10 UTC, Ekwav commented on api/ApiHelper.tsx
> +                toast.error('You need to be logged in to purchase something.')
```suggestion
                toast.error('You need to be logged in to save privacy settings.')
```

2022-05-12 17:17 UTC, Ekwav approved these changes

2022-05-12 17:17 UTC, merged