added range slider element for enchantment level filter
matthias-luger/hypixel-react pull request #850
Opened 2022-06-23 15:13 UTC by matthias-luger

fixes #693

2022-06-25 11:47 UTC, Ekwav requested changes
Doesn't work from URL
Breaks existing filters such as `>5` `<5`
requires two clicks and two drags of slider just to select lvl 6, could you optimise that?
Slider overlaps with other elements, it should have a bit of right and left padding

2022-07-03 11:46 UTC, Ekwav requested changes
works as expected :+1: 
The input field could be made smaller tho
<img width="491" alt="image" src="https://user-images.githubusercontent.com/16632490/177038130-86fe5557-a51b-4919-84c2-d6f9ea102507.png">

2022-07-04 12:29 UTC, matthias-luger commented
The field was already smaller than that, I now made it even smaller though...
![image](https://user-images.githubusercontent.com/58751503/177155124-02d1b80a-85dc-44f3-a032-b07b2d4051c4.png)
![image](https://user-images.githubusercontent.com/58751503/177155160-64692ae8-b924-4c3a-a0d2-4c80d229451d.png)

2022-07-04 12:55 UTC, Ekwav approved these changes

2022-07-04 12:55 UTC, merged