simplify flipper settings
matthias-luger/hypixel-react pull request #913
Opened 2022-09-13 03:02 UTC by matthias-luger

2022-09-13 03:03 UTC, matthias-luger commented
@Ekwav Could you maybe check this out and just take a quick look at it, if this is what you had in mind?

2022-09-19 01:20 UTC, matthias-luger commented
@Ekwav bump

2022-09-29 20:24 UTC, Ekwav requested changes

2022-09-29 20:24 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +        return flipCustomizeSettings.finders?.length === 1 && flipCustomizeSettings.finders[0] === 2
I am not sure why but this doesn't work, when selecting only the `sniper` in `settings` it still displays median

2022-09-29 20:24 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +            flipCustomizeSettings.useLowestBinForProfit = true
```suggestion
```
that setting is deprecated, please avoid activating it

2022-09-29 20:24 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +                                tooltipContent={<span>Minimum amount of sold auctions in the last 24 hours</span>}
```suggestion
                                tooltipContent={<span>Minimum average amount of sells in 24 hours</span>}
```
its mostly not the last 24 hours but longer/shorter timespans

2022-09-29 20:24 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +                            tooltipContent={<span>Edit flip appaerance and general settings</span>}
```suggestion
                            tooltipContent={<span>Edit flip appearance and general settings</span>}
```

2022-09-29 20:24 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +                                <span>Dont show auction flips that are about to end and could be profited from with the current bid</span>
```suggestion
                                <span>Do not show auction flips that are about to end and could be profited from with the current bid</span>
```

2022-09-29 20:24 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +                            content={<span className={`${styles.flipperFilterFormfieldLabel} ${styles.checkboxLabel}`}>Blacklist</span>}
```suggestion
                            content={<span className={`${styles.flipperFilterFormfieldLabel} ${styles.checkboxLabel}`}>Filter-Rules</span>}
```
whitelists are often overlooked

2022-09-29 20:24 UTC, Ekwav commented on components/Flipper/FlipperFilter/FlipperFilter.tsx
> +                            content={<span className={`${styles.flipperFilterFormfieldLabel} ${styles.checkboxLabel}`}>Blacklist</span>}
```suggestion
                            content={<span className={`${styles.flipperFilterFormfieldLabel} ${styles.checkboxLabel}`}>Filter-Rules</span>}
```
whitelists are often overlooked

2022-10-08 12:42 UTC, Ekwav approved these changes
LGTM!

2022-10-08 12:42 UTC, merged